# Site settings
title: 'NaMi Home'  # Your Title
tagline: '但愿你的眼睛 只看得到笑容
但愿你流下每一滴泪都让人感动
但愿你以后每一个梦不会一场空'  # A brief tagline for your site
sidebar_image: /images/cover.jpg


# Build settings
encoding: UTF-8
markdown: kramdown
#markdown: redcarpet
highlighter: pygments
#highlighter: true
baseurl: # the subpath of your site, e.g. /blog/